### ISSUE TITLE
[Bug] In Camera VFX project mode, blinking issue is shown.

### ISSUE THREAD

**Issue by swanilee** [xverse-engine/XV3DGS-UEPlugin#10]
**Describe the bug**
If the *.ply blueprint is loaded, loaded object is continueously blinking.
Then, play mode or rendering result is now shown that problem.

**To Reproduce**
1. Go to 'InCameraVFX project'
2. Load *.ply as blueprint
3. Click & Drag 'loaded ply blueprint' to display.
5. See error

**Screenshots ( video file )**
https://github.com/xverse-engine/XV3DGS-UEPlugin/assets/26716759/9cc500f5-e427-4ce9-bc41-35d5b7198e3a

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version: 21H2

 - UE version: 5.3.2
 - NVIDIA driver version: 546.29 ( RTX GPU 2080ti )

**Comment by lxk121lalala** [comment]
> **Describe the bug** If the *.ply blueprint is loaded, loaded object is continueously blinking. Then, play mode or rendering result is now shown that problem.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'InCameraVFX project'
> 2. Load *.ply as blueprint
> 3. Click & Drag 'loaded ply blueprint' to display.
> 4. See error
> 
> **Screenshots ( video file )** https://github.com/xverse-engine/XV3DGS-UEPlugin/assets/26716759/9cc500f5-e427-4ce9-bc41-35d5b7198e3a
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10
> * Version: 21H2
> * UE version: 5.3.2
> * NVIDIA driver version: 546.29 ( RTX GPU 2080ti )

We fixed flickers in the just released v1.1.2 version, please try again and contact me if there are any bugs

**Comment by swanilee** [comment]
Thank you for your consideration.
Then, I tested new version today. I found that flickers was still happening. Could you check it out ?

And I wonder that plugin  version seems like "1.0" after changing the new release version.
![image](https://github.com/xverse-engine/XV3DGS-UEPlugin/assets/26716759/5dbaab75-46ea-4ea3-8c8a-6ce0995be6e0)

My desktop version and setting is the same as before. 
( OS: Windows 10
Version: 21H2
UE version: 5.3.2
NVIDIA driver version: 546.29 ( RTX GPU 2080ti ) )

Uploading XV3dGS 2024-02-20 13-49-18.mp4…


Thank you.

**Comment by lxk121lalala** [comment]
#17 Maybe the flicker was  caused by raytracing？
And I wonder if flickers still happening if it is an empty level without any post-processing volume?

**Comment by daydreamerguan** [comment]
If it is convenient, please email the contents of folder doguri to guanmengxiang@xverse.cn so that we can fix this bug soon.
<img width="621" alt="企业微信截图_17084224941622" src="https://github.com/xverse-engine/XV3DGS-UEPlugin/assets/5515845/977b3127-cecd-4c63-96bb-061570d217a3">
Thank you

**Comment by lxk121lalala** [comment]
> Thank you for your consideration. Then, I tested new version today. (v1.1.2) I found that flickers was still happening. Could you check it out ?
> 
> And I wonder , Is it right that plugin version seems like "1.0" after changing the new release version. ![image](https://private-user-images.githubusercontent.com/26716759/306137873-5dbaab75-46ea-4ea3-8c8a-6ce0995be6e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjExMDMsIm5iZiI6MTcwODQyMDgwMywicGF0aCI6Ii8yNjcxNjc1OS8zMDYxMzc4NzMtNWRiYWFiNzUtNDZlYS00ZWEzLThjOGEtNmNlMDk5NWJlNmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA5MjAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNjQ0YWFjYmNmNWNhZWQ2MWRjNjVkNDBjYmJkYWIyYjlmYzhiYmM5ZTM4ZGQyZDBhNzlmZDdlMzdiZDVhZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W0I-6l_aizTaQ6JrVtFndr_sQyk9cw77LHoMyUHie0g)
> 
> My desktop version and setting is the same as above before. ( OS: Windows 10 Version: 21H2 UE version: 5.3.2 NVIDIA driver version: 546.29 ( RTX GPU 2080ti ) .. so on)
> 
>  XV3ds_vfx_test_new.-.Unreal.Editor.2024-02-20.13-54-01.mp4 
> Thank you.

#17  Maybe the flicker was caused by raytracing？
And I wonder if flickers still happening if it is an empty level without any post-processing volume?

**Comment by swanilee** [comment]
@lxk121lalala 

Well, I don't know exactly the reason that came from ray tracing.
When I made the project with VFXCamera , I set no mark with ray tracing.

In empty level setting, the flicker  doesn't appear.

Just in case, I tested other ply file from [polycam website](https://poly.cam/explore?feed=all&filter=splat), then the same problem was shown.

**Comment by pixelpunk-DE** [comment]
Try to add a nDisplay root actor and the flicker will start again.
It has something to do with how nDisplay renders in editor.
When i disable realtime or delete the nDisplay actor it stops.
